name: lc
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.02
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-project=0.8.4
  - applaunchservices=0.2.1
  - appscript=1.1.0
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - astropy=4.0.1.post1
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.8.2
  - bitarray=1.2.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.4
  - blosc=1.18.1
  - bokeh=2.0.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cloudpickle=1.3.0
  - clyent=1.2.2
  - colorama=0.4.3
  - contextlib2=0.6.0.post1
  - cryptography=2.8
  - curl=7.69.1
  - cycler=0.10.0
  - cython=0.29.15
  - cytoolz=0.10.1
  - dask=2.14.0
  - dask-core=2.14.0
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - distributed=2.14.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.1.0
  - ffmpeg=4.2
  - filelock=3.0.12
  - flake8=3.7.9
  - flask=1.1.1
  - fontconfig=2.13.1
  - freetype=2.9.1
  - fsspec=0.7.1
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.4.0
  - giflib=5.2.1
  - glib=2.63.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gnutls=3.6.5
  - graphite2=1.3.13
  - greenlet=0.4.15
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - heapdict=1.0.1
  - html5lib=1.0.1
  - hypothesis=5.8.3
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - imagesize=1.2.0
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jasper=1.900.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.15.2
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.0
  - keyring=21.1.1
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lame=3.100
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - liblief=0.9.0
  - libopencv=4.2.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm-openmp=4.0.1
  - llvmlite=0.31.0
  - locket=0.2.0
  - lxml=4.5.0
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=4.0.1
  - more-itertools=8.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multipledispatch=0.6.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - nettle=3.4.1
  - networkx=2.4
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.48.0
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - opencv=4.2.0
  - openh264=1.8.0
  - openpyxl=3.0.3
  - openssl=1.1.1f
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - partd=1.1.0
  - path=13.1.0
  - path.py=12.4.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-lief=0.9.0
  - py-opencv=4.2.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.4.4
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.4.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.8.0
  - pytest-astropy-header=0.1.2
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.9
  - python-libarchive-c=2.8
  - python.app=2
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qdarkstyle=2.8
  - qt=5.9.7
  - qtawesome=0.7.0
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - ripgrep=11.0.2
  - rope=0.16.0
  - rtree=0.9.3
  - ruamel_yaml=0.15.87
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.14.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=2.0
  - sphinx=2.4.4
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.1
  - spyder=4.1.2
  - spyder-kernels=1.9.0
  - sqlalchemy=1.3.15
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - sympy=1.5.1
  - tbb=2020.0
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.44.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - ujson=1.35
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.25.8
  - watchdog=0.10.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.0.0
  - x264=1!152.20180806
  - xlrd=1.2.0
  - xlsxwriter=1.2.8
  - xlwings=0.18.0
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zict=2.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - autograd==1.3
